from __future__ import annotations


KR_TOP100_NAMES = [
    "삼성전자",
    "SK하이닉스",
    "한화시스템",
    "한미반도체",
    "현대차",
    "LIG넥스원",
    "케이뱅크",
    "S-Oil",
    "두산에너빌리티",
    "한화에어로스페이스",
    "우리기술",
    "한화솔루션",
    "KODEX 200",
    "미래에셋증권",
    "흥구석유",
    "KODEX 200선물인버스2X",
    "KODEX 인버스",
    "에코프로",
    "휴림로봇",
    "리노공업",
    "현대무벡스",
    "한국전력",
    "삼성중공업",
    "NAVER",
    "삼성SDI",
    "현대로템",
    "한화오션",
    "KODEX 코스닥150",
    "풍산",
    "카카오",
    "TIGER 미국S&P500",
    "현대ADM",
    "KODEX 코스닥150레버리지",
    "테크윙",
    "TIGER 반도체TOP10",
    "SK이노베이션",
    "삼천당제약",
    "SK증권",
    "알테오젠",
    "한국항공우주",
    "대한항공",
    "대한광통신",
    "기아",
    "TIGER 반도체TOP10레버리지",
    "LG전자",
    "SK스퀘어",
    "대한전선",
    "삼성SDS",
    "스피어",
    "대우건설",
    "제주반도체",
    "POSCO홀딩스",
    "레인보우로보틱스",
    "극동유화",
    "이수페타시스",
    "우리금융지주",
    "흥아해운",
    "에코프로비엠",
    "HPSP",
    "클로봇",
    "LG에너지솔루션",
    "나무기술",
    "KODEX 레버리지",
    "KODEX 200타겟위클리커버드콜",
    "신한 인버스 2X 코스닥150 선물 ETN",
    "SK텔레콤",
    "셀트리온",
    "펄어비스",
    "KODEX 미국S&P500",
    "N2 월간 레버리지 방위산업 Top5 ETN",
    "HMM",
    "하이브",
    "펩트론",
    "알지노믹스",
    "한화비전",
    "퍼스텍",
    "대한해운",
    "삼성전기",
    "한온시스템",
    "대주전자재료",
    "현대건설",
    "엘앤에프",
    "KODEX 방산TOP10",
    "파마리서치",
    "현대제철",
    "태성",
    "한국석유",
    "TIGER 200",
    "로보티즈",
    "LG씨엔에스",
    "에이비엘바이오",
    "미래에셋생명",
    "카카오뱅크",
    "현대바이오",
    "유진로봇",
    "파두",
    "LS ELECTRIC",
    "DSC인베스트먼트",
    "KEC",
    "ACE KRX금현물",
]


KR_MANUAL_SYMBOLS = {
    "KODEX 200": "069500.KS",
    "KODEX 200선물인버스2X": "252670.KS",
    "KODEX 인버스": "114800.KS",
    "KODEX 코스닥150": "229200.KS",
    "KODEX 코스닥150레버리지": "233740.KS",
    "TIGER 미국S&P500": "360750.KS",
    "TIGER 반도체TOP10": "396500.KS",
    "TIGER 반도체TOP10레버리지": "488080.KS",
    "KODEX 레버리지": "122630.KS",
    "KODEX 200타겟위클리커버드콜": "498400.KS",
    "KODEX 미국S&P500": "379800.KS",
    "KODEX 방산TOP10": "0080G0.KS",
    "TIGER 200": "102110.KS",
    "ACE KRX금현물": "411060.KS",
    "신한 인버스 2X 코스닥150 선물 ETN": "500072.KS",
    "N2 월간 레버리지 방위산업 Top5 ETN": "550092.KS",
}


KR_NAME_ALIASES = {
    "현대차": "현대자동차",
    "한국전력": "한국전력공사",
    "삼성SDS": "삼성에스디에스",
    "한국석유": "한국석유공업",
    "LS ELECTRIC": "엘에스일렉트릭",
    "S-Oil": "에쓰오일",
}


US_TOP100_NAME_SYMBOLS = [
    ("바탈리언 오일", "BATL"),
    ("팔러다인 AI", "PDYN"),
    ("브랜드 인게이지먼트 네트워크", "BNAI"),
    ("블루헷 인터랙티브 엔터테인먼트 테크놀로지", "BHAT"),
    ("객소스 AI", "GXAI"),
    ("트리오 페트롤리엄", "TPET"),
    ("임팩트 바이오메디컬", None),
    ("팔란티어", "PLTR"),
    ("SOXL", "SOXL"),
    ("KORU", "KORU"),
    ("엔비디아", "NVDA"),
    ("아이렌", "IREN"),
    ("테슬라", "TSLA"),
    ("마이크로소프트", "MSFT"),
    ("IRE", "IRE"),
    ("아이온큐", "IONQ"),
    ("써클 인터넷 그룹", "CRCL"),
    ("메리스 테크", "MTEK"),
    ("알파벳 A", "GOOGL"),
    ("TSLL", "TSLL"),
    ("MDJM", "MDJM"),
    ("브로드컴", "AVGO"),
    ("TMD 에너지", None),
    ("퀀스 테라퓨틱스", "QNCX"),
    ("오라클", "ORCL"),
    ("CONL", "CONL"),
    ("리게티 컴퓨팅", "RGTI"),
    ("ETHU", "ETHU"),
    ("넷플릭스", "NFLX"),
    ("PLTU", "PLTU"),
    ("온다스", "ONDS"),
    ("애플", "AAPL"),
    ("디슨트 홀딩", None),
    ("TQQQ", "TQQQ"),
    ("샌디스크", "SNDK"),
    ("로켓 랩", "RKLB"),
    ("아마존", "AMZN"),
    ("GDXU", "GDXU"),
    ("AST 스페이스모바일", "ASTS"),
    ("SES AI", "SES"),
    ("레드와이어", "RDW"),
    ("QQQM", "QQQM"),
    ("RGTX", "RGTX"),
    ("SOXS", "SOXS"),
    ("SCHD", "SCHD"),
    ("RGTZ", "RGTZ"),
    ("앨토 인그리디언츠", "ALTO"),
    ("오션펄", None),
    ("BMNU", "BMNU"),
    ("QQQ", "QQQ"),
    ("JEPQ", "JEPQ"),
    ("IONX", "IONX"),
    ("VCI 글로벌", "VCIG"),
    ("VOO", "VOO"),
    ("마이크론 테크놀로지", "MU"),
    ("NVDL", "NVDL"),
    ("IREZ", "IREZ"),
    ("로빈 에너지", None),
    ("리졸브 AI", "RZLV"),
    ("비트마인 이머션 테크놀로지스", "BMNR"),
    ("SNXX", "SNXX"),
    ("바이오엑셀 테라퓨틱스", "BTAI"),
    ("인텔", "INTC"),
    ("EWY", "EWY"),
    ("누부루", "BURU"),
    ("뉴스케일파워", "SMR"),
    ("QLD", "QLD"),
    ("MSTU", "MSTU"),
    ("코카콜라", "KO"),
    ("조비 에비에이션", "JOBY"),
    ("메디커스 파마", None),
    ("템퍼스 AI", "TEM"),
    ("CRCA", "CRCA"),
    ("앱러빈", "APP"),
    ("ORCX", "ORCX"),
    ("씰SQ", "LAES"),
    ("에어로바이런먼트", "AVAV"),
    ("코인베이스", "COIN"),
    ("메타", "META"),
    ("AMD", "AMD"),
    ("쿠팡", "CPNG"),
    ("인도네시아 에너지", "INDO"),
    ("유니티 소프트웨어", "U"),
    ("EON 리소시스", "EONR"),
    ("MSFU", "MSFU"),
    ("ASTX", "ASTX"),
    ("로빈후드", "HOOD"),
    ("AGQ", "AGQ"),
    ("US 에너지", "USEG"),
    ("오클로", "OKLO"),
    ("SPYM", "SPYM"),
    ("퓨전 퓨얼 그린", "HTOO"),
    ("SLV", "SLV"),
    ("플래닛 랩스", "PL"),
    ("파이어플라이 뉴로사이언스", "AIFF"),
    ("일라이 릴리", "LLY"),
    ("스트래티지", "MSTR"),
    ("레드 캣 홀딩스", "RCAT"),
    ("노보노디스크(ADR)", "NVO"),
    ("OKLL", "OKLL"),
]


US_NAME_QUERY_OVERRIDES = {
    "팔란티어": "Palantir",
    "엔비디아": "NVIDIA",
    "아이렌": "IREN",
    "테슬라": "Tesla",
    "마이크로소프트": "Microsoft",
    "아이온큐": "IonQ",
    "알파벳 A": "Alphabet Class A",
    "브로드컴": "Broadcom",
    "리게티 컴퓨팅": "Rigetti Computing",
    "넷플릭스": "Netflix",
    "온다스": "Ondas",
    "애플": "Apple",
    "샌디스크": "Sandisk",
    "로켓 랩": "Rocket Lab",
    "아마존": "Amazon",
    "AST 스페이스모바일": "AST SpaceMobile",
    "레드와이어": "Redwire",
    "앨토 인그리디언츠": "Alto Ingredients",
    "마이크론 테크놀로지": "Micron",
    "바이오엑셀 테라퓨틱스": "BioXcel Therapeutics",
    "인텔": "Intel",
    "뉴스케일파워": "NuScale Power",
    "코카콜라": "Coca-Cola",
    "조비 에비에이션": "Joby Aviation",
    "템퍼스 AI": "Tempus AI",
    "앱러빈": "AppLovin",
    "씰SQ": "SEALSQ",
    "에어로바이런먼트": "AeroVironment",
    "코인베이스": "Coinbase",
    "메타": "Meta Platforms",
    "쿠팡": "Coupang",
    "유니티 소프트웨어": "Unity Software",
    "오클로": "Oklo",
    "퓨전 퓨얼 그린": "Fusion Fuel Green",
    "플래닛 랩스": "Planet Labs",
    "일라이 릴리": "Eli Lilly",
    "스트래티지": "MicroStrategy",
    "레드 캣 홀딩스": "Red Cat Holdings",
    "노보노디스크(ADR)": "Novo Nordisk ADR",
}
